version: '3.3'
volumes:
  LE:

networks:
  traefik-network:
services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    volumes:
      - 'LE:/letsencrypt/'
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 8080:8080
      - 80:80
      - 44334:443
    networks:
      - traefik-network
  announcements:
    container_name: announcements
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.announcement.rule=Host(`live.chasbob.co.uk`)"
      - "traefik.http.routers.announcement.entrypoints=web"
      - "traefik.http.routers.announcement.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.HTTPtoHTTPS.redirectscheme.scheme=https"
      - "traefik.http.services.announcement.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network

